// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokemonGolotEF.Data;

#nullable disable

namespace PokemonGolotEF.Migrations
{
    [DbContext(typeof(PokemonGolotDBContext))]
    partial class PokemonGolotDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PokemonGolotEF.Model.Egg", b =>
                {
                    b.Property<double>("km_egg")
                        .HasColumnType("double precision");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("km_egg");

                    b.ToTable("Egg");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.EggInventory", b =>
                {
                    b.Property<double>("egg")
                        .HasColumnType("double precision");

                    b.Property<string>("user")
                        .HasColumnType("character varying(20)");

                    b.Property<double>("remainingKm")
                        .HasColumnType("double precision");

                    b.HasKey("egg", "user");

                    b.HasIndex("user");

                    b.ToTable("Egg_inventory");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.Element", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("image")
                        .HasColumnType("text");

                    b.HasKey("name");

                    b.ToTable("Element");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.EvolutionChain", b =>
                {
                    b.Property<int>("pokemon_base")
                        .HasColumnType("integer");

                    b.Property<int>("pokemon_evolved")
                        .HasColumnType("integer");

                    b.Property<int>("candy_needed")
                        .HasColumnType("integer");

                    b.HasKey("pokemon_base", "pokemon_evolved");

                    b.HasIndex("pokemon_evolved");

                    b.ToTable("Evolution_chain");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.Friendship", b =>
                {
                    b.Property<string>("user")
                        .HasColumnType("character varying(20)");

                    b.Property<string>("friend")
                        .HasColumnType("character varying(20)");

                    b.HasKey("user", "friend");

                    b.HasIndex("friend");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.Gym", b =>
                {
                    b.Property<string>("location")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("team")
                        .HasColumnType("text");

                    b.HasKey("location");

                    b.HasIndex("team");

                    b.ToTable("Gym");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.GymDefense", b =>
                {
                    b.Property<string>("gym")
                        .HasColumnType("text");

                    b.Property<int>("pokemon")
                        .HasColumnType("integer");

                    b.Property<int>("defenseTime")
                        .HasColumnType("integer");

                    b.Property<int>("timesFeeded")
                        .HasColumnType("integer");

                    b.HasKey("gym", "pokemon");

                    b.HasIndex("pokemon");

                    b.ToTable("Gym_defensors");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.GymTrophy", b =>
                {
                    b.Property<string>("gym")
                        .HasColumnType("text");

                    b.Property<string>("user")
                        .HasColumnType("character varying(20)");

                    b.Property<int>("fights_won")
                        .HasColumnType("integer");

                    b.Property<int>("pokemon_time")
                        .HasColumnType("integer");

                    b.Property<int>("times_feeded")
                        .HasColumnType("integer");

                    b.HasKey("gym", "user");

                    b.HasIndex("user");

                    b.ToTable("Gym_trophies");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.Level", b =>
                {
                    b.Property<short>("level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("level"));

                    b.Property<int>("necessary_xp")
                        .HasColumnType("integer");

                    b.HasKey("level");

                    b.ToTable("Level");

                    b.HasData(
                        new
                        {
                            level = (short)1,
                            necessary_xp = 0
                        },
                        new
                        {
                            level = (short)2,
                            necessary_xp = 1000
                        },
                        new
                        {
                            level = (short)3,
                            necessary_xp = 3000
                        },
                        new
                        {
                            level = (short)4,
                            necessary_xp = 6000
                        },
                        new
                        {
                            level = (short)5,
                            necessary_xp = 10000
                        },
                        new
                        {
                            level = (short)6,
                            necessary_xp = 15000
                        },
                        new
                        {
                            level = (short)7,
                            necessary_xp = 21000
                        },
                        new
                        {
                            level = (short)8,
                            necessary_xp = 28000
                        },
                        new
                        {
                            level = (short)9,
                            necessary_xp = 36000
                        },
                        new
                        {
                            level = (short)10,
                            necessary_xp = 45000
                        },
                        new
                        {
                            level = (short)11,
                            necessary_xp = 55000
                        },
                        new
                        {
                            level = (short)12,
                            necessary_xp = 65000
                        },
                        new
                        {
                            level = (short)13,
                            necessary_xp = 75000
                        },
                        new
                        {
                            level = (short)14,
                            necessary_xp = 85000
                        },
                        new
                        {
                            level = (short)15,
                            necessary_xp = 100000
                        },
                        new
                        {
                            level = (short)16,
                            necessary_xp = 120000
                        },
                        new
                        {
                            level = (short)17,
                            necessary_xp = 140000
                        },
                        new
                        {
                            level = (short)18,
                            necessary_xp = 160000
                        },
                        new
                        {
                            level = (short)19,
                            necessary_xp = 185000
                        },
                        new
                        {
                            level = (short)20,
                            necessary_xp = 210000
                        },
                        new
                        {
                            level = (short)21,
                            necessary_xp = 260000
                        },
                        new
                        {
                            level = (short)22,
                            necessary_xp = 335000
                        },
                        new
                        {
                            level = (short)23,
                            necessary_xp = 435000
                        },
                        new
                        {
                            level = (short)24,
                            necessary_xp = 560000
                        },
                        new
                        {
                            level = (short)25,
                            necessary_xp = 710000
                        },
                        new
                        {
                            level = (short)26,
                            necessary_xp = 900000
                        },
                        new
                        {
                            level = (short)27,
                            necessary_xp = 1100000
                        },
                        new
                        {
                            level = (short)28,
                            necessary_xp = 1350000
                        },
                        new
                        {
                            level = (short)29,
                            necessary_xp = 1650000
                        },
                        new
                        {
                            level = (short)30,
                            necessary_xp = 2000000
                        },
                        new
                        {
                            level = (short)31,
                            necessary_xp = 2500000
                        },
                        new
                        {
                            level = (short)32,
                            necessary_xp = 3000000
                        },
                        new
                        {
                            level = (short)33,
                            necessary_xp = 3750000
                        },
                        new
                        {
                            level = (short)34,
                            necessary_xp = 4750000
                        },
                        new
                        {
                            level = (short)35,
                            necessary_xp = 6000000
                        },
                        new
                        {
                            level = (short)36,
                            necessary_xp = 7500000
                        },
                        new
                        {
                            level = (short)37,
                            necessary_xp = 9500000
                        },
                        new
                        {
                            level = (short)38,
                            necessary_xp = 12000000
                        },
                        new
                        {
                            level = (short)39,
                            necessary_xp = 15000000
                        },
                        new
                        {
                            level = (short)40,
                            necessary_xp = 20000000
                        },
                        new
                        {
                            level = (short)41,
                            necessary_xp = 26000000
                        },
                        new
                        {
                            level = (short)42,
                            necessary_xp = 33500000
                        },
                        new
                        {
                            level = (short)43,
                            necessary_xp = 42500000
                        },
                        new
                        {
                            level = (short)44,
                            necessary_xp = 53500000
                        },
                        new
                        {
                            level = (short)45,
                            necessary_xp = 66500000
                        },
                        new
                        {
                            level = (short)46,
                            necessary_xp = 82000000
                        },
                        new
                        {
                            level = (short)47,
                            necessary_xp = 100000000
                        },
                        new
                        {
                            level = (short)48,
                            necessary_xp = 121000000
                        },
                        new
                        {
                            level = (short)49,
                            necessary_xp = 146000000
                        },
                        new
                        {
                            level = (short)50,
                            necessary_xp = 176000000
                        });
                });

            modelBuilder.Entity("PokemonGolotEF.Model.LevelupObjectReward", b =>
                {
                    b.Property<short>("level")
                        .HasColumnType("smallint");

                    b.Property<string>("object_name")
                        .HasColumnType("text");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.HasKey("level", "object_name");

                    b.HasIndex("object_name");

                    b.ToTable("Levelup_object_rewards");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.Movement", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<int>("duration")
                        .HasColumnType("integer");

                    b.Property<string>("element")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("energy")
                        .HasColumnType("double precision");

                    b.Property<int>("power")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("name");

                    b.HasIndex("element");

                    b.ToTable("Movement");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.Object", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("name");

                    b.ToTable("Object");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.ObjectInventory", b =>
                {
                    b.Property<string>("objectName")
                        .HasColumnType("text");

                    b.Property<string>("user")
                        .HasColumnType("character varying(20)");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.HasKey("objectName", "user");

                    b.HasIndex("user");

                    b.ToTable("Object_inventories");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.PackageItems", b =>
                {
                    b.Property<string>("objectName")
                        .HasColumnType("text");

                    b.Property<string>("package")
                        .HasColumnType("text");

                    b.Property<int>("units")
                        .HasColumnType("integer");

                    b.HasKey("objectName", "package");

                    b.HasIndex("package");

                    b.ToTable("Package_items");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.PackageOffer", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<double>("price")
                        .HasColumnType("double precision");

                    b.HasKey("name");

                    b.ToTable("Package_offer");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.PackageOfferBought", b =>
                {
                    b.Property<string>("package")
                        .HasColumnType("text");

                    b.Property<string>("user")
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("last_bought_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("package", "user");

                    b.HasIndex("user");

                    b.ToTable("Package_offers_bought");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.Pokemon", b =>
                {
                    b.Property<int>("num_pokedex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("num_pokedex"));

                    b.Property<double>("attack")
                        .HasColumnType("double precision");

                    b.Property<double>("defense")
                        .HasColumnType("double precision");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("female_gender")
                        .HasColumnType("boolean");

                    b.Property<string>("img_back")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("img_front")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("male_gender")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("rarity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("stamina")
                        .HasColumnType("double precision");

                    b.HasKey("num_pokedex");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.PokemonLevel", b =>
                {
                    b.Property<float>("pokemon_level")
                        .HasColumnType("real");

                    b.Property<int>("candy_to_upgrade")
                        .HasColumnType("integer");

                    b.Property<double>("pc_multiplier")
                        .HasColumnType("double precision");

                    b.Property<int>("stardust_to_upgrade")
                        .HasColumnType("integer");

                    b.HasKey("pokemon_level");

                    b.ToTable("Pokemon_level");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.PokemonOwned", b =>
                {
                    b.Property<int>("pokemonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("pokemonId"));

                    b.Property<int>("atack_iv")
                        .HasColumnType("integer");

                    b.Property<int>("defense_iv")
                        .HasColumnType("integer");

                    b.Property<float>("level")
                        .HasColumnType("real");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("owner")
                        .IsRequired()
                        .HasColumnType("character varying(20)");

                    b.Property<int>("pokemon")
                        .HasColumnType("integer");

                    b.Property<int>("stamina_iv")
                        .HasColumnType("integer");

                    b.HasKey("pokemonId");

                    b.HasIndex("level");

                    b.HasIndex("owner");

                    b.HasIndex("pokemon");

                    b.ToTable("Pokemon_owned");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.PokemonRegister", b =>
                {
                    b.Property<int>("pokemon")
                        .HasColumnType("integer");

                    b.Property<string>("user")
                        .HasColumnType("character varying(20)");

                    b.Property<char>("gender")
                        .HasColumnType("character(1)");

                    b.Property<int>("capturedNumber")
                        .HasColumnType("integer");

                    b.Property<int>("height")
                        .HasColumnType("integer");

                    b.Property<bool>("sawed")
                        .HasColumnType("boolean");

                    b.Property<double>("weight")
                        .HasColumnType("double precision");

                    b.HasKey("pokemon", "user", "gender");

                    b.HasIndex("user");

                    b.ToTable("Pokemon_register");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.PokeStop", b =>
                {
                    b.Property<string>("location")
                        .HasColumnType("text");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("location");

                    b.ToTable("PokeStop");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.Present", b =>
                {
                    b.Property<int>("presentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("presentId"));

                    b.Property<DateTime>("getDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("opened")
                        .HasColumnType("boolean");

                    b.Property<string>("owner")
                        .IsRequired()
                        .HasColumnType("character varying(20)");

                    b.Property<string>("pokeStop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("receptor")
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("sendDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("presentId");

                    b.HasIndex("owner");

                    b.HasIndex("pokeStop");

                    b.HasIndex("receptor");

                    b.ToTable("Present");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.Raid", b =>
                {
                    b.Property<string>("location")
                        .HasColumnType("text");

                    b.Property<int>("boss")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("location");

                    b.HasIndex("boss");

                    b.ToTable("Raid");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.RaidParticipant", b =>
                {
                    b.Property<string>("gym")
                        .HasColumnType("text");

                    b.Property<string>("user")
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Raidlocation")
                        .HasColumnType("text");

                    b.HasKey("gym", "user");

                    b.HasIndex("Raidlocation");

                    b.HasIndex("user");

                    b.ToTable("Raid_participants");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.Team", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("name");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.TypeTable", b =>
                {
                    b.Property<string>("element")
                        .HasColumnType("text");

                    b.Property<string>("affected_element")
                        .HasColumnType("text");

                    b.Property<double>("multiplier")
                        .HasColumnType("double precision");

                    b.HasKey("element", "affected_element");

                    b.HasIndex("affected_element");

                    b.ToTable("Type_table");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.User", b =>
                {
                    b.Property<string>("user_name")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("birth_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("caputred_pokemon")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char>("gender")
                        .HasColumnType("character(1)");

                    b.Property<int>("inventory_capacity")
                        .HasColumnType("integer");

                    b.Property<short>("level")
                        .HasColumnType("smallint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("pokemon_slots")
                        .HasColumnType("integer");

                    b.Property<int>("remaining_experience")
                        .HasColumnType("integer");

                    b.Property<string>("team")
                        .HasColumnType("text");

                    b.Property<int>("won_battles")
                        .HasColumnType("integer");

                    b.HasKey("user_name");

                    b.HasIndex("level");

                    b.HasIndex("team");

                    b.ToTable("User");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.EggInventory", b =>
                {
                    b.HasOne("PokemonGolotEF.Model.Egg", "Egg")
                        .WithMany()
                        .HasForeignKey("egg")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonGolotEF.Model.User", "User")
                        .WithMany("eggs")
                        .HasForeignKey("user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Egg");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.EvolutionChain", b =>
                {
                    b.HasOne("PokemonGolotEF.Model.Pokemon", "PokemonBase")
                        .WithMany()
                        .HasForeignKey("pokemon_base")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonGolotEF.Model.Pokemon", "PokemonEvolved")
                        .WithMany()
                        .HasForeignKey("pokemon_evolved")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PokemonBase");

                    b.Navigation("PokemonEvolved");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.Friendship", b =>
                {
                    b.HasOne("PokemonGolotEF.Model.User", "Friend")
                        .WithMany("friends")
                        .HasForeignKey("friend")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonGolotEF.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.Gym", b =>
                {
                    b.HasOne("PokemonGolotEF.Model.PokeStop", "PokeStop")
                        .WithMany()
                        .HasForeignKey("location")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonGolotEF.Model.Team", "Team")
                        .WithMany("Gyms")
                        .HasForeignKey("team");

                    b.Navigation("PokeStop");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.GymDefense", b =>
                {
                    b.HasOne("PokemonGolotEF.Model.Gym", "Gym")
                        .WithMany("defensors")
                        .HasForeignKey("gym")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonGolotEF.Model.Pokemon", "Pokemon")
                        .WithMany()
                        .HasForeignKey("pokemon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.GymTrophy", b =>
                {
                    b.HasOne("PokemonGolotEF.Model.Gym", "Gym")
                        .WithMany()
                        .HasForeignKey("gym")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonGolotEF.Model.User", "User")
                        .WithMany("trophys")
                        .HasForeignKey("user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.LevelupObjectReward", b =>
                {
                    b.HasOne("PokemonGolotEF.Model.Level", "Level")
                        .WithMany("rewards")
                        .HasForeignKey("level")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonGolotEF.Model.Object", "Object")
                        .WithMany("levels")
                        .HasForeignKey("object_name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.Movement", b =>
                {
                    b.HasOne("PokemonGolotEF.Model.Element", "Element")
                        .WithMany()
                        .HasForeignKey("element")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.ObjectInventory", b =>
                {
                    b.HasOne("PokemonGolotEF.Model.Object", "Object")
                        .WithMany()
                        .HasForeignKey("objectName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonGolotEF.Model.User", "User")
                        .WithMany("inventory")
                        .HasForeignKey("user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Object");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.PackageItems", b =>
                {
                    b.HasOne("PokemonGolotEF.Model.Object", "Object")
                        .WithMany()
                        .HasForeignKey("objectName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonGolotEF.Model.PackageOffer", "Package")
                        .WithMany("Items")
                        .HasForeignKey("package")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Object");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.PackageOfferBought", b =>
                {
                    b.HasOne("PokemonGolotEF.Model.PackageOffer", "Package")
                        .WithMany("buyers")
                        .HasForeignKey("package")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonGolotEF.Model.User", "User")
                        .WithMany("packagesOfferBought")
                        .HasForeignKey("user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.PokemonOwned", b =>
                {
                    b.HasOne("PokemonGolotEF.Model.PokemonLevel", "Level")
                        .WithMany("pokemons")
                        .HasForeignKey("level")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonGolotEF.Model.User", "Owner")
                        .WithMany("pokemons")
                        .HasForeignKey("owner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonGolotEF.Model.Pokemon", "Pokemon")
                        .WithMany("Owners")
                        .HasForeignKey("pokemon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("Owner");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.PokemonRegister", b =>
                {
                    b.HasOne("PokemonGolotEF.Model.Pokemon", "Pokemon")
                        .WithMany()
                        .HasForeignKey("pokemon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonGolotEF.Model.User", "User")
                        .WithMany("pokedex")
                        .HasForeignKey("user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.Present", b =>
                {
                    b.HasOne("PokemonGolotEF.Model.User", "Owner")
                        .WithMany("presentsToSend")
                        .HasForeignKey("owner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonGolotEF.Model.PokeStop", "PokeStop")
                        .WithMany("presents")
                        .HasForeignKey("pokeStop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonGolotEF.Model.User", "Receptor")
                        .WithMany("recivedPresents")
                        .HasForeignKey("receptor");

                    b.Navigation("Owner");

                    b.Navigation("PokeStop");

                    b.Navigation("Receptor");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.Raid", b =>
                {
                    b.HasOne("PokemonGolotEF.Model.Pokemon", "Pokemon")
                        .WithMany()
                        .HasForeignKey("boss")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonGolotEF.Model.Gym", "Gym")
                        .WithMany("raids")
                        .HasForeignKey("location")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.RaidParticipant", b =>
                {
                    b.HasOne("PokemonGolotEF.Model.Raid", null)
                        .WithMany("Participants")
                        .HasForeignKey("Raidlocation");

                    b.HasOne("PokemonGolotEF.Model.Gym", "Gym")
                        .WithMany()
                        .HasForeignKey("gym")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonGolotEF.Model.User", "User")
                        .WithMany("raidsParticipated")
                        .HasForeignKey("user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.TypeTable", b =>
                {
                    b.HasOne("PokemonGolotEF.Model.Element", "Affected_element")
                        .WithMany()
                        .HasForeignKey("affected_element")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonGolotEF.Model.Element", "Element")
                        .WithMany()
                        .HasForeignKey("element")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Affected_element");

                    b.Navigation("Element");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.User", b =>
                {
                    b.HasOne("PokemonGolotEF.Model.Level", "Level")
                        .WithMany("users")
                        .HasForeignKey("level")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonGolotEF.Model.Team", "Team")
                        .WithMany("Users")
                        .HasForeignKey("team");

                    b.Navigation("Level");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.Gym", b =>
                {
                    b.Navigation("defensors");

                    b.Navigation("raids");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.Level", b =>
                {
                    b.Navigation("rewards");

                    b.Navigation("users");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.Object", b =>
                {
                    b.Navigation("levels");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.PackageOffer", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("buyers");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.Pokemon", b =>
                {
                    b.Navigation("Owners");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.PokemonLevel", b =>
                {
                    b.Navigation("pokemons");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.PokeStop", b =>
                {
                    b.Navigation("presents");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.Raid", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.Team", b =>
                {
                    b.Navigation("Gyms");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PokemonGolotEF.Model.User", b =>
                {
                    b.Navigation("eggs");

                    b.Navigation("friends");

                    b.Navigation("inventory");

                    b.Navigation("packagesOfferBought");

                    b.Navigation("pokedex");

                    b.Navigation("pokemons");

                    b.Navigation("presentsToSend");

                    b.Navigation("raidsParticipated");

                    b.Navigation("recivedPresents");

                    b.Navigation("trophys");
                });
#pragma warning restore 612, 618
        }
    }
}
